<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-1MVI6MI9" ignored="0" name="RetryTCS" tests="6" failures="2" timestamp="2022-01-13T13:07:36 IST" time="0.075" errors="0">
  <testcase name="testcase1" time="0.012" classname="RunTimeRetryFailedTC.Test02">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.001" classname="RunTimeRetryFailedTC.Test02">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.001" classname="RunTimeRetryFailedTC.Test02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RunTimeRetryFailedTC.Test02.testcase1(Test02.java:9)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase2" time="0.002" classname="RunTimeRetryFailedTC.Test02">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.001" classname="RunTimeRetryFailedTC.Test02">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.001" classname="RunTimeRetryFailedTC.Test02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RunTimeRetryFailedTC.Test02.testcase2(Test02.java:13)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- RetryTCS -->
